#!/bin/sh

cd tests

error()
{
    echo "ERROR during test '$curtest', quitting"
    exit 1
}


for curtest in test-*.smx
do
	if [ -e "$curtest.skip"  ]; then
		echo "$curtest ... skipping"
	else
		echo $curtest
		../smx $curtest > $curtest.tmp
		if [ -e $curtest.ok2 ]; then
			if ( ! diff $curtest.ok $curtest.tmp ) && ( ! diff $curtest.ok2 $curtest.tmp ); then error; fi
		else
			if ! diff $curtest.ok $curtest.tmp; then error; fi
		fi
	fi
done

curtest="safemode.smx"
if [ -e "$curtest.skip"  ]; then
        echo "$curtest ... skipping"
else
	echo $curtest

	pw=`which pw 2> /dev/null`
	if [ "$pw" != "" ]; then 
		pw useradd smxsafemodeuser -s /dev/null
	else 
		useradd smxsafemodeuser -s /dev/null -M
	fi
	mkdir safemodedir
	chown smxsafemodeuser safemodedir
	cp safemode.smx safemodedir
	chown smxsafemodeuser "safemodedir/safemode.smx"

	../smx "safemodedir/safemode.smx" > safemode.tmp

	if [ "$pw" != "" ]; then 
		pw userdel smxsafemodeuser
	else
		userdel smxsafemodeuser
	fi
	rm -rf safemodedir

	if ! diff safemode.ok safemode.tmp; then error; fi
fi

rm -f *.tmp
