#!/bin/sh

error()
{
    echo "ERROR during test '$curtest', quitting"
    kill `cat test_httpd.pid` 2> /dev/null
    exit 1
}

cd tests 2> /dev/null
LIBEXECDIR=`apxs -q LIBEXECDIR`
if [ "$LIBEXECDIR" != "" ]; then
	sed "s|@LIBEXECDIR@|$LIBEXECDIR|" test.conf.in > test.conf
else
	sed "s|@LIBEXECDIR@|modules|" test.conf.in > test.conf
fi

pw=`which pw 2> /dev/null`
if [ "$pw" != "" ]; then
	pw useradd test_httpd_user -d `pwd` -s /dev/null
else
	useradd test_httpd_user -d `pwd` -s /dev/null -M
fi
rm -rf test_data 
mkdir test_data
chown test_httpd_user:test_httpd_user test_data
httpd -f `pwd`/test.conf

for curtest in test-*.html
do
        if [ -e "$curtest.skip"  ]; then
                echo "$curtest ... skipping"
        else
                echo $curtest
                wget -q http://127.0.0.1:55558/$curtest -O $curtest.tmp
                if ! diff $curtest.ok $curtest.tmp; then error; fi
        fi
done

httpd -f `pwd`/test.conf -k stop
kill `cat test_httpd.pid`

if [ "$pw" != "" ]; then
        pw userdel test_httpd_user
else
        userdel test_httpd_user
fi
rm -rf test_data 
