# New ports collection makefile for:   smx
# Date created:        11 March 2009
# Whom:                erik
#
# $FreeBSD$
#

PORTNAME=      smx
DISTVERSION=   1.1.4-356
CATEGORIES=    lang
MASTER_SITES=  http://smx.googlecode.com/files/

MAINTAINER=    erik@q32.com
COMMENT=       Easy to use language for building dynamic websites

GNU_CONFIGURE= yes
WRKSRC=	       ${WRKDIR}/smx-1.1.4

.include <bsd.port.mk>
